import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from '@/components/LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import { LogOutBtn } from '@/components/LogOutBtn'
import { cookies } from 'next/headers'
import DarkMode from './DarkMode'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // server component 에서 로그인된 유저 정보 출력
  // * 보통 server component 에서 유저 정보 가져와서 client component 로 전송해주는 게 나음 (client component는 html 렌더링 후 실행될 수 있기 때문)
  let session = await getServerSession(authOptions);
  // console.log(session);

  // server component 에서 쿠키 쓰기
  let mode = cookies().get('mode');

  return (
    <html lang="en">
      <body className={mode?.value === 'dark' ? 'dark-mode' : ''}>
        <div className="navbar"> 
          <Link href="/" className="logo">Appleforum</Link> 
          <Link href="/list">List</Link>
          {
            session ?
            <span>{session.user.name} <LogOutBtn /></span> :
            <LoginBtn />
          }
          <DarkMode mode={mode?.value} />
        </div>
        {children}
      </body>
    </html>
  )
}
